2025-03-25 14:15:31,928 - ERROR - 查询 => 签约团队: 已签约
2025-03-25 14:15:34,104 - INFO - 查询 => {'姓名': '胡成', '身份证号': '110101199001014999', '签约日期': [[2025, 1, 2], [2025, 2, 3]], '签约服务包': '基础服务包（2019版）', '签约机构': '张星卫生院', '签约团队': '已签约', '履约情况': '未履约', '居民基本信息': ['一般人群', '孕产妇'], '家庭地址': '123个人'}
2025-03-25 14:17:23,961 - INFO - 查询 => {'姓名': '胡成', '身份证号': '110101199001014999', '签约日期': [[2025, 1, 2], [2025, 2, 3]], '签约服务包': '基础服务包（2019版）', '签约机构': '张星卫生院', '履约情况': '未履约', '居民基本信息': ['一般人群', '孕产妇'], '家庭地址': '123个人'}
2025-03-27 15:01:51,659 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:01:51,661 - INFO - {'operate': '查看', 'data': {}}
2025-03-27 15:01:51,662 - INFO - {'operate': '履约', 'data': {}}
2025-03-27 15:03:41,380 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:05:02,452 - INFO - Received signal: SIGINT
2025-03-27 15:05:02,452 - INFO - Program is terminating...
2025-03-27 15:05:02,825 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083d420>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,828 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083dfc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,830 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083e1a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,833 - ERROR - 失败 =>{'operate': '查看', 'data': {}}
2025-03-27 15:05:02,835 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083e4d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,837 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083e680>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,840 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083e830>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,845 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083ec50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,848 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083ee30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,850 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d080b5e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,854 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083e260>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,856 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083df60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,858 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083ddb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,863 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083d900>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,865 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083ef50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,867 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083f100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,871 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083f460>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,873 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083f5b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,875 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083f700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,880 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083fb50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,882 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083fd30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,884 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d083fee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,889 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d0878220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,892 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d0878400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,895 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d08785b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,899 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d08789d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,901 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d0878bb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,907 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe1d0878d60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d6a85cdafe5a2cf79f3c0f868349f965/element
2025-03-27 15:05:02,910 - ERROR - 失败 =>{'operate': '履约', 'data': {}}
2025-03-27 15:05:21,898 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:05:28,458 - INFO - {'operate': '查看', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:05:33,868 - ERROR - 失败 =>{'operate': '履约', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:07:06,627 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:07:13,118 - INFO - {'operate': '查看', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:10:53,727 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:11:00,290 - INFO - {'operate': '查看', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:11:59,140 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:12:05,638 - INFO - {'operate': '查看', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:13:29,422 - INFO - 查询 => {'身份证号': '310101197712137029'}
2025-03-27 15:13:35,916 - INFO - {'operate': '查看', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:13:40,017 - INFO - {'operate': '查看', 'data': {}}
2025-03-27 15:13:46,521 - INFO - {'operate': '履约', 'option': {'身份证号': '310101197712137029'}}
2025-03-27 15:13:48,684 - INFO - {'operate': '履约', 'data': {}}
