{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n>       assert False\nE       assert False\n\ntest_allure_command.py:21: AssertionError"}, "start": 1744018270162, "stop": 1744018270162, "uuid": "4797829a-a341-45f1-a348-76381c605a20", "historyId": "45ca17d263822c8490205f9b7d863d97", "testCaseId": "45ca17d263822c8490205f9b7d863d97", "fullName": "test_allure_command#test_failure", "labels": [{"name": "suite", "value": "test_allure_command"}, {"name": "host", "value": "localhost-2.local"}, {"name": "thread", "value": "18330-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_command"}]}