{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_allure_command.py:27: Exception"}, "start": 1744018270276, "stop": 1744018270276, "uuid": "5a5c0aaf-e419-42f3-b230-c1b974bf760c", "historyId": "07a313684a28626cc8b25a29e78367b8", "testCaseId": "07a313684a28626cc8b25a29e78367b8", "fullName": "test_allure_command#test_broken", "labels": [{"name": "suite", "value": "test_allure_command"}, {"name": "host", "value": "localhost-2.local"}, {"name": "thread", "value": "18330-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_command"}]}