2025-03-21 14:17:17,764 - ERROR - 查询 => 年龄: [2, 5]
2025-03-21 14:17:53,150 - INFO - 查询 => {'管理机构': '招远市卫健局', '档案状态': '在档', '姓名': '胡成', '年龄': [2, 5], '身份证号': '372922198510281068', '联系电话': '58776544'}
2025-03-21 14:20:55,289 - INFO - Received signal: SIGINT
2025-03-21 14:20:55,292 - INFO - Program is terminating...
2025-03-21 14:20:55,341 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683c730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,343 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683cbb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,348 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683ce80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,353 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683d150>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,355 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683d330>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,358 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683d4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,366 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683d900>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,369 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683dae0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,372 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683dc90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,378 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683e0b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,386 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683e290>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,388 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683e440>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,394 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683e860>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,398 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683ea40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,401 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683ebf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,406 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683f010>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,408 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683f1f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,410 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683f3a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,416 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683f7c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,419 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683f9a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:20:55,421 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f841683fb50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/decc92650efc947dff0f96fba8ed4d93/element
2025-03-21 14:21:45,368 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:21:51,781 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:31:48,440 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:31:54,828 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:32:12,563 - ERROR - 失败 =>{'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
2025-03-21 14:48:05,839 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:48:12,244 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:48:29,984 - ERROR - 失败 =>{'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
2025-03-21 14:51:47,815 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:51:54,197 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:52:20,549 - ERROR - 失败 =>{'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
2025-03-21 14:53:58,865 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:54:05,259 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:54:22,845 - ERROR - 失败 =>{'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
2025-03-21 14:56:09,905 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:56:16,274 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:56:35,833 - ERROR - 失败 =>{'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
2025-03-21 14:57:47,026 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 14:57:53,400 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 14:58:14,417 - ERROR - 失败 =>{'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
2025-03-21 15:00:04,960 - INFO - 查询 => {'身份证号': '370685199001012654'}
2025-03-21 15:00:11,367 - INFO - {'operate': '新增登记', 'option': {'身份证号': '370685199001012654'}}
2025-03-21 15:00:51,553 - INFO - {'operate': '冠心病患者登记', 'data': {'冠心病诊断': '冠心病猝死', '诊断依据': 'CT', '发病日期': [2025, 1, 2], '确认日期': [2025, 1, 3], '确诊医院': '阿里医院', '是否首次发病': '是', '登记日期': [2025, 1, 4], '开始管理时间': [2025, 1, 5]}}
